wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/train.py
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1653238270
    t:
      1:
      - 1
      - 9
      - 11
      - 33
      - 41
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.12.16
      6: 4.11.3
      8:
      - 5
b1:
  desc: null
  value: 0.9
b2:
  desc: null
  value: 0.999
batch_size:
  desc: null
  value: 8
e:
  desc: null
  value: 1.0e-08
epochs:
  desc: null
  value: 3
l2:
  desc: null
  value: 0.01
lr:
  desc: null
  value: 6.25e-05
max_grad_norm:
  desc: null
  value: 1
n_ctx:
  desc: null
  value: 256
schedule:
  desc: null
  value: warmup_linear
vector_l2:
  desc: null
  value: store_true
warmup:
  desc: null
  value: 0.002
